### ISSUE TITLE
Build Errors on Lines 94-95

### ISSUE THREAD

**Issue by redoctopus** [evan-erdos/CMU.ADV#12]
The lack of obj/web and obj/cmd files seems to be adversely affecting attempts at assembly.

**Comment by evan-erdos** [comment]
you might have to create the folders yourself, but since they're not part of the repo, the build script should do so.

Are you able to build?

**Comment by redoctopus** [comment]
Ah, yeah. Didn't build until I manually created empty folders obj/web and obj/cmd.
Should we add these to the repo or were they taken out just to be cleaner (I seem to remember them existing a few weeks ago)?

**Comment by evan-erdos** [comment]
fixed, plz pull
