### ISSUE TITLE
Doesn't take user input for name

### ISSUE THREAD

**Issue by redoctopus** [evan-erdos/CMU.ADV#14]
It keeps looping the prompts for name and gender. Occasionally it seems to assign a default name, though I've only been able to get it to do this twice and can't remember how to repro it.

**Comment by evan-erdos** [comment]
!

that's weird. 
I usually just press enter repeatedly until I'm on campus.

**Comment by fseidel** [comment]
Can confirm. Was able to replicate bug on my machine.

**Comment by redoctopus** [comment]
Ah, yes. That seems to work. But what if I want to play as my normal female test character, "sdfsfs"?!

**Comment by evan-erdos** [comment]
yeah, I'm almost done fixing this.
It's a real hack to get it to wait around before starting the game, actually

**Comment by evan-erdos** [comment]
> what if I want to play as my normal female test character, "sdfsfs"?!

now you can!

**Comment by redoctopus** [comment]
Wunderbar. sdfsfs will rise again.
